# Generated by Django 3.2.3 on 2021-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_words_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.CharField(default='no example', max_length=100),
        ),
    ]
